org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.2
enabled_platforms=fabric,neoforge

maven_group=net.zelythia
archives_name=autotools
mod_version=3.4.4

cloth_config_version=26.2.155
controllable_version=0.26.0+26.1.1


# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.152.2+26.2
modmenu_version=20.0.0-beta.4

# Forge
forge_version=1.21.11-61.0.3

# Neoforge
neoforge_version=26.2.0.7-beta

